export const CATEGORIES = [
  { id: 1, name: "Food", icon: "🍜", color: "#FFD700" },
  { id: 2, name: "Bills/Utilities", icon: "💡", color: "#FFA07A" },
  { id: 3, name: "Family", icon: "👨‍👩‍👧", color: "#90EE90" },
  { id: 4, name: "Healthcare", icon: "🏥", color: "#FF7F7F" },
  { id: 5, name: "Fuel", icon: "⛽", color: "#FF8C00" },
  { id: 6, name: "Phone/Internet", icon: "📱", color: "#87CEEB" },
  { id: 7, name: "Education", icon: "📚", color: "#9370DB" },
  { id: 8, name: "Entertainment", icon: "🎬", color: "#E6E6FA" },
  { id: 9, name: "Shopping", icon: "🛍️", color: "#FF69B4" },
  { id: 10, name: "Travel", icon: "✈️", color: "#00CED1" },
  { id: 11, name: "Socializing", icon: "🍻", color: "#CD853F" },
  { id: 12, name: "Withdrawal", icon: "🏧", color: "#D3D3D3" },
  { id: 13, name: "Transfer", icon: "🔄", color: "#32CD32" },
  { id: 14, name: "Transportation", icon: "🚗", color: "#FFA500" },
  { id: 15, name: "Housing", icon: "🏠", color: "#ADD8E6" },
  { id: 16, name: "Miscellaneous", icon: "📦", color: "#808080" },
];

export const expensesData = [
  {
    id: "1",
    icon: "🛒",
    title: "Grocery Shopping",
    category: "Groceries",
    amount: 250.0,
    date: "2026-03-01",
    color: "#FFD700",
  },
  {
    id: "2",
    icon: "☕",
    title: "Coffee",
    category: "Beverages",
    amount: 100.0,
    date: "2026-03-02",
    color: "#FFA500",
  },
  {
    id: "3",
    icon: "🍔",
    title: "Lunch",
    category: "Food",
    amount: 180.0,
    date: "2026-03-03",
    color: "#FF8C00",
  },
  {
    id: "4",
    icon: "🚕",
    title: "Taxi Ride",
    category: "Travel",
    amount: 320.0,
    date: "2026-03-04",
    color: "#1E90FF",
  },
  {
    id: "5",
    icon: "🎬",
    title: "Movie Ticket",
    category: "Entertainment",
    amount: 450.0,
    date: "2026-03-05",
    color: "#9370DB",
  },
  {
    id: "6",
    icon: "💡",
    title: "Electricity Bill",
    category: "Utilities",
    amount: 1200.0,
    date: "2026-03-06",
    color: "#FFD700",
  },
  {
    id: "7",
    icon: "🛍️",
    title: "Clothing",
    category: "Shopping",
    amount: 900.0,
    date: "2026-03-07",
    color: "#FF69B4",
  },
  {
    id: "8",
    icon: "⛽",
    title: "Fuel",
    category: "Transport",
    amount: 700.0,
    date: "2026-03-08",
    color: "#DC143C",
  },
];